# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(),
        ),
    ]
