# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0002_auto_20170307_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
