# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='text',
            new_name='rating',
        ),
    ]
