# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0005_auto_20170317_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.CharField(default='wadteam1', max_length=128),
        ),
    ]
