# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0006_auto_20170320_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.CharField(max_length=128),
        ),
    ]
