# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0007_auto_20170318_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='playlists',
        ),
        migrations.AddField(
            model_name='comment',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='ToP.Playlist'),
        ),
    ]
