# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToP', '0008_auto_20170319_1348'),
        ('ToP', '0006_auto_20170320_1132'),
    ]

    operations = [
    ]
